waProyectoEF/Models/Habitacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace waProyectoEF.Models
{
    public class Habitacion
    {
        [DisplayName("CÓDIGO")]
        public int ide_hab { get; set; }

        [DisplayName("NÚMERO HABITACIÓN")]
        public String num_hab { get; set; }

        [DisplayName("TIPO HABITACIÓN")]
        public String nom_tha { get; set; }

        [DisplayName("CAPACIDAD")]
        public int cap_hab { get; set; }

        [DisplayName("PRECIO")]
        public double pre_hab { get; set; }

        [DisplayName("ESTADO")]
        public String nom_est { get; set; }
    }
}

waProyectoEF/Controllers/HabitacionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using waProyectoEF.Models;

namespace waProyectoEF.Controllers
{
    public class HabitacionController : Controller
    {
        //Obtener la cadena de conexion
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);

        //Arreglo de habitaciones (Listar las habitaciones)
        public List<Habitacion> aHabitaciones()
        {
            List<Habitacion> aHabitaciones = new List<Habitacion>();
            cn.Open();
            SqlCommand cmd = new SqlCommand("SP_LISTARHABITACIONES", cn);
            cmd.CommandType = CommandType.StoredProcedure;

            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aHabitaciones.Add(new Habitacion()
                {
                    ide_hab = int.Parse(dr[0].ToString()),
                    num_hab = dr[1].ToString(),
                    nom_tha = dr[2].ToString(),
                    cap_hab = int.Parse(dr[3].ToString()),
                    pre_hab = double.Parse(dr[4].ToString()),
                    nom_est = dr[5].ToString()

                });
            }
            cn.Close();
            return aHabitaciones;
        }


        //Arreglo de habitaciones (Arreglo con columnas originales)
        public List<HabitacionO> aHabitacionesO()
        {
            List<HabitacionO> aHabitacionesO = new List<HabitacionO>();
            cn.Open();
            SqlCommand cmd = new SqlCommand("SP_LISTARHABITACIONES_O", cn);
            cmd.CommandType = CommandType.StoredProcedure;

            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aHabitacionesO.Add(new HabitacionO()
                {
                    ide_hab = int.Parse(dr[0].ToString()),
                    num_hab = dr[1].ToString(),
                    ide_tha = int.Parse(dr[2].ToString()),
                    cap_hab = int.Parse(dr[3].ToString()),
                    pre_hab = double.Parse(dr[4].ToString()),
                    ide_est = int.Parse(dr[5].ToString())

                });
            }
            cn.Close();
            return aHabitacionesO;
        }

        //Arreglo para estados (combobox)
        public List<Estado> aEstados()
        {
            List<Estado> aEstados = new List<Estado>();
            cn.Open();
            SqlCommand cmd = new SqlCommand("SP_LISTARESTADO", cn);
            cmd.CommandType = CommandType.StoredProcedure;

            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aEstados.Add(new Estado()
                {
                    ide_est = int.Parse(dr[0].ToString()),
                    nom_est = dr[1].ToString()
                });
            }
            cn.Close();
            return aEstados;
        }

        //Arreglo para habitaciones x estado
        public List<Habitacion> aHabitacionesxEstado(int est)
        {
            List<Habitacion> aHabitacionesxEstado = new List<Habitacion>();
            cn.Open();

            SqlCommand cmd = new SqlCommand("SP_LISTAHABITACIONESxESTADO", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@IDE_EST", est);
            //cmd.Parameters.Add("@VEN", SqlDbType.Int).Value = ven;

            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aHabitacionesxEstado.Add(new Habitacion()
                {
                    ide_hab = int.Parse(dr[0].ToString()),
                    num_hab = dr[1].ToString(),
                    nom_tha = dr[2].ToString(),
                    cap_hab = int.Parse(dr[3].ToString()),
                    pre_hab = double.Parse(dr[4].ToString()),
                    nom_est = dr[5].ToString()

                });
            }
            cn.Close();
            return aHabitacionesxEstado;
        }

        //Arreglo para tipo (combobox)
        public List<Tipo> aTipos()
        {
            List<Tipo> aTipos = new List<Tipo>();
            cn.Open();
            SqlCommand cmd = new SqlCommand("SP_LISTARTIPO", cn);
            cmd.CommandType = CommandType.StoredProcedure;

            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aTipos.Add(new Tipo()
                {
                    ide_tha = int.Parse(dr[0].ToString()),
                    nom_tha = dr[1].ToString()
                });
            }
            cn.Close();
            return aTipos;
        }

        //Arreglo para habitaciones x tipo
        public List<Habitacion> aHabitacionesxTipo(int tip)
        {
            List<Habitacion> aHabitacionesxTipo = new List<Habitacion>();
            cn.Open();

            SqlCommand cmd = new SqlCommand("SP_LISTAHABITACIONESxTIPO", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@IDE_THA", tip);
            //cmd.Parameters.Add("@VEN", SqlDbType.Int).Value = ven;

            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aHabitacionesxTipo.Add(new Habitacion()
                {
                    ide_hab = int.Parse(dr[0].ToString()),
                    num_hab = dr[1].ToString(),
                    nom_tha = dr[2].ToString(),
                    cap_hab = int.Parse(dr[3].ToString()),
                    pre_hab = double.Parse(dr[4].ToString()),
                    nom_est = dr[5].ToString()

                });
            }
            cn.Close();
            return aHabitacionesxTipo;
        }


        private int obtenerSiguienteCodigo()
        {
            int siguienteCodigo = 1; // Código inicial si no hay habitaciones registrados

            // Corregir la declaración del bloque using
            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString))
            {
                cn.Open();

                SqlCommand cmd = new SqlCommand("SELECT MAX(IDE_HAB) FROM Habitaciones", cn);
                object result = cmd.ExecuteScalar();
                if (result != null && result != DBNull.Value)
                {
                    siguienteCodigo = Convert.ToInt32(result) + 1;
                }
            }

            return siguienteCodigo;
        }

        // Método para validar si ya existe un número de habitación registrado
        private bool existeNumeroHabitacion(string num_hab)
        {
            bool existe = false;

            using (SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString))
            {
                cn.Open();

                SqlCommand cmd = new SqlCommand("SELECT COUNT(*) FROM Habitaciones WHERE NUM_HAB = @NUM_HAB", cn);
                cmd.Parameters.AddWithValue("@NUM_HAB", num_hab);

                int count = (int)cmd.ExecuteScalar();
                if (count > 0)
                {
                    existe = true;
                }
            }

            return existe;
        }



        //Nueva Habitación
        [HttpGet]
        public ActionResult nuevaHabitacion()
        {
            int siguienteCodigo = obtenerSiguienteCodigo();
            ViewBag.estados = new SelectList(aEstados(), "ide_est", "nom_est");
            ViewBag.tipos = new SelectList(aTipos(), "ide_tha", "nom_tha");
            ViewBag.SiguienteCodigo = siguienteCodigo;
            return View(new HabitacionO());
        }

        [HttpPost]
        public ActionResult nuevaHabitacion(HabitacionO objH)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.estados = new SelectList(aEstados(), "ide_est", "nom_est", objH.ide_est);
                ViewBag.tipos = new SelectList(aTipos(), "ide_tha", "nom_tha", objH.ide_tha);
                ViewBag.SiguienteCodigo = objH.ide_hab;
                return View(objH);
            }

            // Validar si el número de habitación ya existe
            if (existeNumeroHabitacion(objH.num_hab))
            {
                ModelState.AddModelError("num_hab", "El número de habitación ya está registrado.");
                ViewBag.estados = new SelectList(aEstados(), "ide_est", "nom_est", objH.ide_est);
                ViewBag.tipos = new SelectList(aTipos(), "ide_tha", "nom_tha", objH.ide_tha);
                ViewBag.SiguienteCodigo = objH.ide_hab;
                return View(objH);
            }

            cn.Open();
            SqlCommand cmd = new SqlCommand("SP_NUEVAHABITACION", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@NUM_HAB", objH.num_hab);
            cmd.Parameters.AddWithValue("@IDE_THA", objH.ide_tha);
            cmd.Parameters.AddWithValue("@CAP_HAB", objH.cap_hab);
            cmd.Parameters.AddWithValue("@PRE_HAB", objH.pre_hab);
            cmd.Parameters.AddWithValue("@IDE_EST", objH.ide_est);
            cmd.ExecuteNonQuery();
            cn.Close();

            return RedirectToAction("listadoHabitaciones");

        }
        //Actualiza Habitación
        [HttpGet]
        public ActionResult actualizaHabitacion(int id)
        {
            HabitacionO objH = aHabitacionesO().Where(h => h.ide_hab == id).FirstOrDefault();

            ViewBag.estados = new SelectList(aEstados(), "ide_est", "nom_est", objH.ide_est);
            ViewBag.tipos = new SelectList(aTipos(), "ide_tha", "nom_tha", objH.ide_tha);
            return View(objH);
        }
        [HttpPost]
        public ActionResult actualizaHabitacion(HabitacionO objH)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.estados = new SelectList(aEstados(), "ide_est", "nom_est", objH.ide_est);

waProyectoEF/Views/Habitacion/actualizaHabitacion.cshtml
@model waProyectoEF.Models.HabitacionO

@{
    ViewBag.Title = "actualizaHabitacion";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Actualizar Habitación</h3></div>
                    <div class="card-body">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                        <div class="row mb-3">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.ide_hab, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.ide_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Código de Habitación</label>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.num_hab, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.num_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Número de Habitación</label>
                                </div>
                            </div>

                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.DropDownListFor(model => model.ide_tha,(SelectList)ViewBag.tipos, new { @class = "form-select" } )
                                    @Html.ValidationMessageFor(model => model.ide_tha, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Código</label>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.cap_hab, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.cap_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Código</label>
                                </div>
                            </div>
                        </div>


                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.pre_hab, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.pre_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Código</label>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.DropDownListFor(model => model.ide_est, (SelectList)ViewBag.estados,new { @class = "form-select" } )
                                    @Html.ValidationMessageFor(model => model.ide_est, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Código</label>
                                </div>
                            </div>
                        </div>


                                <div class="form-group">
                                    <div class="mt-4 mb-0">
                                        <div class="d-grid">
                                            <input type="submit" value="Modificar" class="btn btn-primary btn-block" />
                                        </div>
                                    </div>
                                </div>
                                }
                            </div>
                        </div>
            </div>
        </div>
    </div>
</main>

waProyectoEF/Views/Habitacion/listadoHabitaciones.cshtml
@model IEnumerable<waProyectoEF.Models.Habitacion>

@{
    ViewBag.Title = "listadoHabitaciones";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Tablas</h1>
        <div class="mb-4 d-flex">
            <a href="@Url.Action("listadoHabitacionesxEstado", "Habitacion")" class="btn btn-primary me-2">
                Ver Habitaciones por Estado
            </a>
            <a href="@Url.Action("listadoHabitacionesxTipo", "Habitacion")" class="btn btn-primary">
                Ver Habitaciones por Tipo
            </a>
        </div>

        <div class="card mb-4">
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Listado Habitaciones
            </div>
            <div class="card-body">
                <table id="datatablesSimple">

                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ide_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.num_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nom_tha)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cap_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.pre_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nom_est)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ide_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.num_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nom_tha)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cap_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.pre_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nom_est)
                            </td>
                            <td>
                                @Html.ActionLink("Modificar", "actualizaHabitacion", new { id = item.ide_hab }) |
                                <a href="javascript:void(0);" onclick="confirmarEliminacion('@Url.Action("eliminaHabitacion", new { id = item.ide_hab })')">Eliminar</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</main>

<script>
    function confirmarEliminacion(url) {
        Swal.fire({
            title: '¿Estás seguro?',
            text: "¡No podrás revertir esto!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí, eliminarlo!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url;
            }
        })
    }
</script>

waProyectoEF/Views/Habitacion/listadoHabitacionesxEstado.cshtml
@model IEnumerable<waProyectoEF.Models.Habitacion>

@{
    ViewBag.Title = "listadoHabitacionesxEstado";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<br />
<div class="container-fluid px-4">
    <div class="row mb-4">
        <div class="col-md-3">
            @using (Html.BeginForm())
            {
                <div class="input-group">
                    @Html.DropDownList("est", (SelectList)ViewBag.estados, new { @class = "form-select" })
                    <button class="btn btn-primary" type="submit">BUSCAR</button>
                </div>
            }
        </div>
        <div class="col-md-3">
            <a href="@Url.Action("listadoHabitaciones", "Habitacion")" class="btn btn-secondary">
                Volver
            </a>
        </div>
    </div>
</div>
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Tablas</h1>
        <div class="card mb-4">
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Filtrar Habitaciones por Estado
            </div>
            <div class="card-body">
                <table id="datatablesSimple">

                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ide_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.num_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nom_tha)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cap_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.pre_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nom_est)
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ide_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.num_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nom_tha)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cap_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.pre_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nom_est)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</main>

waProyectoEF/Views/Habitacion/listadoHabitacionesxTipo.cshtml
@model IEnumerable<waProyectoEF.Models.Habitacion>

@{
    ViewBag.Title = "listadoHabitacionesxTipo";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<br />
<div class="container-fluid px-4">
    <div class="row mb-4">
        <div class="col-md-3">
            @using (Html.BeginForm())
            {
                <div class="input-group">
                    @Html.DropDownList("tip", (SelectList)ViewBag.tipos, new { @class = "form-select" })
                    <button class="btn btn-primary" type="submit">BUSCAR</button>
                </div>
            }
        </div>
        <div class="col-md-3">
            <a href="@Url.Action("listadoHabitaciones", "Habitacion")" class="btn btn-secondary">
                Volver
            </a>
        </div>
    </div>
</div>

<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Tablas</h1>
        <div class="card mb-4">
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Filtrar Habitaciones por Tipo
            </div>
            <div class="card-body">
                <table id="datatablesSimple">

                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ide_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.num_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nom_tha)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.cap_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.pre_hab)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.nom_est)
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ide_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.num_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nom_tha)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cap_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.pre_hab)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.nom_est)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</main>

waProyectoEF/Views/Habitacion/nuevaHabitacion.cshtml
@model waProyectoEF.Models.HabitacionO

@{
    ViewBag.Title = "nuevaHabitacion";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Registrar Nueva Habitación</h3></div>
                    <div class="card-body">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                        <div class="row mb-3">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.TextBoxFor(model => model.ide_hab,new { @class = "form-control", @readonly = "readonly", @Value = ViewBag.SiguienteCodigo })
                                    @Html.ValidationMessageFor(model => model.ide_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Código de Habitación</label>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.num_hab, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.num_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Número de Habitación</label>
                                </div>
                            </div>
                        </div>


                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.DropDownListFor(model => model.ide_tha,(SelectList)ViewBag.tipos, new { @class = "form-select" } )
                                    @Html.ValidationMessageFor(model => model.ide_tha, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Tipo de Habitación</label>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.cap_hab, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.cap_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Capacidad</label>
                                </div>
                            </div>

                        </div>


                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.EditorFor(model => model.pre_hab, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.pre_hab, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Precio</label>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-floating mb-3 mb-md-0">
                                    @Html.DropDownListFor(model => model.ide_est,(SelectList)ViewBag.estados, new { @class = "form-select" } )
                                    @Html.ValidationMessageFor(model => model.ide_est, "", new { @class = "text-danger" })
                                    <label for="inputFirstName">Estado</label>
                                </div>
                            </div>
                        </div>

                                <div class="form-group">
                                    <div class="mt-4 mb-0">
                                        <div class="d-grid">
                                            <input type="submit" value="Registrar" class="btn btn-primary btn-block" />
                                        </div>
                                    </div>
                                </div>
                                }
                            </div>
                        </div>
            </div>
        </div>
    </div>
</main>